// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqfH3BSSuWzVdJKn6Ab6YXukSZhVRdJUM',
    appId: '1:995406752835:web:31006335b05dca6ef838f6',
    messagingSenderId: '995406752835',
    projectId: 'drrmis-aeddc',
    authDomain: 'drrmis-aeddc.firebaseapp.com',
    storageBucket: 'drrmis-aeddc.firebasestorage.app',
    measurementId: 'G-179SGNCZBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Ks407ljr2SttK3KI_rtP4t7YWxkO9aI',
    appId: '1:995406752835:android:626e8a3736c54626f838f6',
    messagingSenderId: '995406752835',
    projectId: 'drrmis-aeddc',
    storageBucket: 'drrmis-aeddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4P9QUldmOCdphlE2Wd50NzsQWtsHWsxM',
    appId: '1:995406752835:ios:7abeae5ef8acfd3cf838f6',
    messagingSenderId: '995406752835',
    projectId: 'drrmis-aeddc',
    storageBucket: 'drrmis-aeddc.firebasestorage.app',
    iosClientId: '995406752835-q83afdifcb8rjhb7ge2jkrhkna2voqpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.drrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4P9QUldmOCdphlE2Wd50NzsQWtsHWsxM',
    appId: '1:995406752835:ios:7abeae5ef8acfd3cf838f6',
    messagingSenderId: '995406752835',
    projectId: 'drrmis-aeddc',
    storageBucket: 'drrmis-aeddc.firebasestorage.app',
    iosClientId: '995406752835-q83afdifcb8rjhb7ge2jkrhkna2voqpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.drrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqfH3BSSuWzVdJKn6Ab6YXukSZhVRdJUM',
    appId: '1:995406752835:web:7b1828b3a660a750f838f6',
    messagingSenderId: '995406752835',
    projectId: 'drrmis-aeddc',
    authDomain: 'drrmis-aeddc.firebaseapp.com',
    storageBucket: 'drrmis-aeddc.firebasestorage.app',
    measurementId: 'G-X1NF37V2YJ',
  );
}
